name: Release Please

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        id: release
        uses: google-github-actions/release-please-action@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}
          release-type: go
          package-name: "MageComm"

      - name: Log release info
        run: |
          echo "New version: ${{ steps.release.outputs.release_version }}"
          echo "PR URL: ${{ steps.release.outputs.pr_url }}"