name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        id: release
        uses: googleapis/release-please-action@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}
          release-type: go
          package-name: "MageComm"
          extra-files: |
            version.txt

      - name: Log release info
        run: |
          echo "New version: ${{ steps.release.outputs.release_version }}"
          echo "PR URL: ${{ steps.release.outputs.pr_url }}"